# Generated by Django 3.2.12 on 2022-07-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.FileField(max_length=50, upload_to='application/photos/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='resume',
            field=models.FileField(max_length=50, upload_to='application/resume/'),
        ),
    ]
