# Generated by Django 3.2.12 on 2022-07-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20220729_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='extmail',
            new_name='secemail',
        ),
    ]
