# Generated by Django 3.2.12 on 2022-07-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_rename_extmail_contact_secemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='secemail',
            new_name='extemail',
        ),
    ]
